### ISSUE TITLE
Very dark in 2018.3

### ISSUE THREAD

**Issue by jejacks0n** [nezix/Unity-GeoAO#1]
Hey, first, thanks for putting this together. I can see how it's working and that's awesome and super useful for me.

I just cloned the repo and fired it up, when I enter game mode I can see that it processes by the logging, but then the dragon is just very dark. Any idea on what might've changed, or what path I should maybe start down on if I were to submit a PR?

**Comment by nezix** [comment]
Hey,

Thank you for posting this. 
I didn't try the latest version of Unity so I can't tell for sure but usually, the errors come from the shader that checks the depth of objects.
The name of the shader is https://github.com/nezix/Unity-GeoAO/blob/master/Assets/Resources/Shaders/VertexAOCompute.shader

I can have a look tomorrow.

**Comment by nezix** [comment]
Hello again,

That seems to work for me on Unity 2018.3.0f2 :

![image](https://user-images.githubusercontent.com/9949327/51465261-ddb56380-1d67-11e9-8aba-c2ce3f505dc5.png)

You can adjust parameters of the shader to show the AO : 

![image](https://user-images.githubusercontent.com/9949327/51465300-f02f9d00-1d67-11e9-8d27-f613c5f2c895.png)

Tested on Windows 10 / DX11

@jejacks0n  Can you tell me on what system did you try ?
